DOMAIN = "radio_france"

NAME = "Radio France"
CONF_API_KEY = "api_key"
CONF_RADIO_STATION = "radio_station"

STATIONS_LIST_STUB = {
    "brands": [
        {
            "id": "FRANCEINTER",
            "title": "France Inter",
            "baseline": "Le direct de France Inter",
            "description": "Joyeuse, savante et populaire, France Inter est la radio généraliste de service public ",
            "websiteUrl": "https://radiofrance.fr",
            "playerUrl": "https://embed.radiofrance.fr/franceinter/player?id_station=1",
            "liveStream": "https://icecast.radiofrance.fr/franceinter-midfi.mp3?id=openapi",
            "localRadios": None,
            "webRadios": None,
        },
        {
            "id": "FRANCEINFO",
            "title": "franceinfo",
            "baseline": "Et tout est plus clair",
            "description": "L'actualité en direct et en continu avec le média global du service public",
            "websiteUrl": "https://radiofrance.fr",
            "playerUrl": "https://embed.radiofrance.fr/franceinfo/player?id_station=2",
            "liveStream": "https://icecast.radiofrance.fr/franceinfo-midfi.mp3?id=openapi",
            "localRadios": None,
            "webRadios": None,
        },
        {
            "id": "FRANCEMUSIQUE",
            "title": "France Musique",
            "baseline": "Ce monde a besoin de musique",
            "description": "Classique mais pas que… Chaque jour, la musique se vit intensément sur France Musique.",
            "websiteUrl": "https://radiofrance.fr",
            "playerUrl": "https://embed.radiofrance.fr/francemusique/player?id_station=4",
            "liveStream": "https://icecast.radiofrance.fr/francemusique-midfi.mp3?id=openapi",
            "localRadios": None,
            "webRadios": [
                {
                    "id": "FRANCEMUSIQUE_CLASSIQUE_EASY",
                    "title": "Classique Easy",
                    "description": "Pour vous concentrer, travailler ou vous détendre, écoutez un flux musical continu diffusant les titres incontournables de la musique classique. ",
                    "liveStream": "https://icecast.radiofrance.fr/francemusiqueeasyclassique-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francemusique/player?id_station=401",
                },
                {
                    "id": "FRANCEMUSIQUE_CLASSIQUE_PLUS",
                    "title": "Classique Plus",
                    "description": "France Musique vous emmène plus loin dans le monde du classique avec une sélection d’œuvres moins ou peu connues à écouter en intégralité. ",
                    "liveStream": "https://icecast.radiofrance.fr/francemusiqueclassiqueplus-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francemusique/player?id_station=402",
                },
                {
                    "id": "FRANCEMUSIQUE_CONCERT_RF",
                    "title": "Concerts Radio France",
                    "description": "Écoutez une grande sélection d'enregistrements de concerts des orchestres et des chœurs de Radio France, avec des solistes et chefs d'orchestre de renom. ",
                    "liveStream": "https://icecast.radiofrance.fr/francemusiqueconcertsradiofrance-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francemusique/player?id_station=403",
                },
                {
                    "id": "FRANCEMUSIQUE_OCORA_MONDE",
                    "title": "Ocora Musiques du Monde",
                    "description": "Voyagez à travers la musique traditionnelle du monde entier avec les innombrables enregistrements du label Ocora disponibles à l’écoute en ligne. ",
                    "liveStream": "https://icecast.radiofrance.fr/francemusiqueocoramonde-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francemusique/player?id_station=404",
                },
                {
                    "id": "FRANCEMUSIQUE_LA_JAZZ",
                    "title": "La Jazz",
                    "description": "Écoutez des enregistrements acoustiques rares et des reprises électriques des standards du jazz depuis ses débuts jusqu’au jazz contemporain d’aujourd’hui. ",
                    "liveStream": "https://icecast.radiofrance.fr/francemusiquelajazz-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francemusique/player?id_station=405",
                },
                {
                    "id": "FRANCEMUSIQUE_LA_CONTEMPORAINE",
                    "title": "La Contemporaine",
                    "description": "Écoutez une musique pleine de liberté et d'innovation, des œuvres expérimentales et classiques de compositeurs vivants de renommée internationale. ",
                    "liveStream": "https://icecast.radiofrance.fr/francemusiquelacontemporaine-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francemusique/player?id_station=406",
                },
                {
                    "id": "FRANCEMUSIQUE_LA_BO",
                    "title": "Musique de Films",
                    "description": "Écoutez les plus beaux extraits de bandes originales, une sélection de musiques de films célèbres, mais aussi d’œuvres rares issues de la plus grande discothèque d’Europe. ",
                    "liveStream": "https://icecast.radiofrance.fr/francemusiquelabo-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francemusique/player?id_station=407",
                },
                {
                    "id": "FRANCEMUSIQUE_LA_BAROQUE",
                    "title": "La Baroque",
                    "description": "Monteverdi, Bach, Haendel, Telemann, les grands compositeurs des XVIIe et XVIIIe siècles à écouter pour un voyage dans l’univers des musiques anciennes. ",
                    "liveStream": "https://icecast.radiofrance.fr/francemusiquebaroque-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francemusique/player?id_station=408",
                },
                {
                    "id": "FRANCEMUSIQUE_OPERA",
                    "title": "Opéra",
                    "description": "L'univers magique de l'opéra avec Verdi, Mozart, Puccini : les plus grands airs interprétés par les plus grandes voix lyriques d'hier et aujourd'hui.",
                    "liveStream": "https://icecast.radiofrance.fr/francemusiqueopera-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francemusique/player?id_station=409",
                },
            ],
        },
        {
            "id": "FRANCECULTURE",
            "title": "France Culture",
            "baseline": "France Culture, l'esprit d'ouverture",
            "description": "",
            "websiteUrl": "https://radiofrance.fr",
            "playerUrl": "https://embed.radiofrance.fr/franceculture/player?id_station=5",
            "liveStream": "https://icecast.radiofrance.fr/franceculture-lofi.mp3?id=openapi",
            "localRadios": None,
            "webRadios": None,
        },
        {
            "id": "MOUV",
            "title": "Mouv'",
            "baseline": "Mouv’, ta radio Hip Hop",
            "description": "La radio jeune et connectée de Radio France : musique, lien social et cultures urbaines.",
            "websiteUrl": "https://radiofrance.fr",
            "playerUrl": "https://embed.radiofrance.fr/mouv/player?id_station=6",
            "liveStream": "https://icecast.radiofrance.fr/mouv-midfi.mp3?id=openapi",
            "localRadios": None,
            "webRadios": [
                {
                    "id": "MOUV_100MIX",
                    "title": "la stream radio Mouv' 100% Mix",
                    "description": "Écoute de la musique sans pub et en illimité avec la radio Mouv’ 100% Mix : DJ First Mike, Dirty Swift, Muxxa, Ayane, Selecta et K-Za.",
                    "liveStream": "https://icecast.radiofrance.fr/mouv100p100mix-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/mouv/player?id_station=75",
                },
                {
                    "id": "MOUV_CLASSICS",
                    "title": "Mouv' Classics",
                    "description": "Écoute gratuitement et sans pub les plus grands classiques du rap et du hip hop sur Mouv’ Classics : les meilleurs sons old school, boom bap, g-funk.",
                    "liveStream": "https://icecast.radiofrance.fr/mouvclassics-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/mouv/player?id_station=601",
                },
                {
                    "id": "MOUV_DANCEHALL",
                    "title": "la stream radio Mouv' DanceHall",
                    "description": "Écoute gratuitement et sans pub le meilleur du reggae et de la musique afro-caribéenne sur la radio en ligne Mouv’ Dancehall : classiques et nouveautés.",
                    "liveStream": "https://icecast.radiofrance.fr/mouvdancehall-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/mouv/player?id_station=602",
                },
                {
                    "id": "MOUV_RNB",
                    "title": "la stream radio Mouv’ RnB & Soul",
                    "description": "Écoute gratuitement et sans pub les meilleurs sons du R'n'B français et US sur la radio en ligne Mouv’ R'n'B & Soul. Beyonce, Rihanna, The Weeknd...",
                    "liveStream": "https://icecast.radiofrance.fr/mouvrnb-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/mouv/player?id_station=603",
                },
                {
                    "id": "MOUV_RAPUS",
                    "title": "la stream radio Mouv' Rap US",
                    "description": "Écoute gratuitement et sans pub le meilleur du rap américain et de la trap sur la radio en ligne Mouv' Rap US : nouveautés, hits et artistes à découvrir.",
                    "liveStream": "https://icecast.radiofrance.fr/mouvrapus-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/mouv/player?id_station=604",
                },
                {
                    "id": "MOUV_RAPFR",
                    "title": "la stream radio Mouv' Rap Français",
                    "description": "Écoute gratuitement et sans pub le meilleur du rap français sur la radio en ligne Mouv' Rap français : avec Booba, Jul, Orelsan, PNL et les stars montantes.",
                    "liveStream": "https://icecast.radiofrance.fr/mouvrapfr-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/mouv/player?id_station=605",
                },
            ],
        },
        {
            "id": "FIP",
            "title": "FIP",
            "baseline": "La radio la plus éclectique du monde",
            "description": "La radio musicale la plus éclectique.",
            "websiteUrl": "https://radiofrance.fr",
            "playerUrl": "https://embed.radiofrance.fr/fip/player?id_station=7",
            "liveStream": "https://icecast.radiofrance.fr/fip-midfi.mp3?id=openapi",
            "localRadios": None,
            "webRadios": [
                {
                    "id": "FIP_ROCK",
                    "title": "FIP Rock",
                    "description": "De Bowie à Radiohead, de Lou Reed à Miossec, FIP conjugue tous les rocks dans une sélection musicale qui traverse les genres et les époques.",
                    "liveStream": "https://icecast.radiofrance.fr/fiprock-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/fip/player?id_station=64",
                },
                {
                    "id": "FIP_JAZZ",
                    "title": "FIP Jazz",
                    "description": "D’Avishai Cohen à Herbie Hancock, de Nina Simone à Christian Scott, retrouvez le swing de FIP dans une sélection musicale qui traverse les genres et les époques.",
                    "liveStream": "https://icecast.radiofrance.fr/fipjazz-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/fip/player?id_station=65",
                },
                {
                    "id": "FIP_GROOVE",
                    "title": "FIP Groove",
                    "description": "De Gil Scott Heron à De la Soul, d’Amy Winehouse à Marvin Gaye, gardez le rythme de FIP dans une sélection musicale qui traverse les genres et les époques.",
                    "liveStream": "https://icecast.radiofrance.fr/fipgroove-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/fip/player?id_station=66",
                },
                {
                    "id": "FIP_WORLD",
                    "title": "FIP Monde",
                    "description": "D’Ibrahim Maalouf à Tony Allen, de Vaudou Game à Bebel Gilberto, franchissez les frontières de FIP dans une sélection musicale qui traverse les genres et les époques.",
                    "liveStream": "https://icecast.radiofrance.fr/fipworld-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/fip/player?id_station=69",
                },
                {
                    "id": "FIP_NOUVEAUTES",
                    "title": "FIP Nouveautés",
                    "description": "Faites le plein de nouveautés avec les meilleures sorties musicales sélectionnées par FIP.",
                    "liveStream": "https://icecast.radiofrance.fr/fipnouveautes-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/fip/player?id_station=70",
                },
                {
                    "id": "FIP_REGGAE",
                    "title": "FIP Reggae",
                    "description": "Des Toots à Biga Ranx, des Clash à DJ Vadim, un voyage vers Zion et au-delà",
                    "liveStream": "https://icecast.radiofrance.fr/fipreggae-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/fip/player?id_station=71",
                },
                {
                    "id": "FIP_ELECTRO",
                    "title": "FIP Electro",
                    "description": "De Air à Soulwax, de Superpoze à Tosca, gardez le kick avec notre sélection électronique",
                    "liveStream": "https://icecast.radiofrance.fr/fipelectro-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/fip/player?id_station=74",
                },
                {
                    "id": "FIP_METAL",
                    "title": "FIP Metal",
                    "description": "Le mix Metal éclectique de Black Sabbath à Deafheaven, de Gojira à Rammstein...",
                    "liveStream": "https://icecast.radiofrance.fr/fipmetal-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/fip/player?id_station=77",
                },
                {
                    "id": "FIP_POP",
                    "title": "FIP Pop",
                    "description": "Découvrez une sélection unique de musiques Pop allant de l'indie-rock à la synth-wave en passant par de la brit-pop à la scène francaise. Avec des artistes incontournables tels que Tame Impala, Jeanne Added, Blur ou Vampire Weekend...",
                    "liveStream": "https://icecast.radiofrance.fr/fippop-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/fip/player?id_station=78",
                },
                {
                    "id": "FIP_HIP_HOP",
                    "title": "FIP Hip-Hop",
                    "description": "Écoutez une programmation qui explore le passé, le présent et le futur du hip-hop. Des Last Poets à Little Simz, de Marcelo D2 à Nujabes en passant par Alpha Wann, plongez dans toute la richesse du rap mondial.",
                    "liveStream": "https://icecast.radiofrance.fr/fiphiphop-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/fip/player?id_station=95",
                },
            ],
        },
        {
            "id": "FRANCEBLEU",
            "title": "France Bleu",
            "baseline": None,
            "description": "",
            "websiteUrl": "https://www.francebleu.fr",
            "playerUrl": None,
            "liveStream": None,
            "localRadios": [
                {
                    "id": "FRANCEBLEU_RCFM",
                    "title": "France Bleu RCFM",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbfrequenzamora-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=11",
                },
                {
                    "id": "FRANCEBLEU_ALSACE",
                    "title": "France Bleu Alsace",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbalsace-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=12",
                },
                {
                    "id": "FRANCEBLEU_ARMORIQUE",
                    "title": "France Bleu Armorique",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbarmorique-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=13",
                },
                {
                    "id": "FRANCEBLEU_AUXERRE",
                    "title": "France Bleu Auxerre",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbauxerre-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=14",
                },
                {
                    "id": "FRANCEBLEU_BEARN",
                    "title": "France Bleu Béarn Bigorre",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbbearn-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=15",
                },
                {
                    "id": "FRANCEBLEU_BELFORT_MONTBELIARD",
                    "title": "France Bleu Belfort-Montbéliard",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbbelfort-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=16",
                },
                {
                    "id": "FRANCEBLEU_BERRY",
                    "title": "France Bleu Berry",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbberry-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=17",
                },
                {
                    "id": "FRANCEBLEU_BESANCON",
                    "title": "France Bleu Besançon",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbbesancon-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=18",
                },
                {
                    "id": "FRANCEBLEU_BOURGOGNE",
                    "title": "France Bleu Bourgogne",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbbourgogne-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=19",
                },
                {
                    "id": "FRANCEBLEU_BREIZH_IZEL",
                    "title": "France Bleu Breizh Izel",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbbreizizel-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=20",
                },
                {
                    "id": "FRANCEBLEU_CHAMPAGNE_ARDENNE",
                    "title": "France Bleu Champagne-Ardenne",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbchampagne-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=21",
                },
                {
                    "id": "FRANCEBLEU_COTENTIN",
                    "title": "France Bleu Cotentin",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbcotentin-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=22",
                },
                {
                    "id": "FRANCEBLEU_CREUSE",
                    "title": "France Bleu Creuse",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbcreuse-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=23",
                },
                {
                    "id": "FRANCEBLEU_DROME_ARDECHE",
                    "title": "France Bleu Drôme Ardèche",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbdromeardeche-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=24",
                },
                {
                    "id": "FRANCEBLEU_GARD_LOZERE",
                    "title": "France Bleu Gard Lozère",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbgardlozere-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=25",
                },
                {
                    "id": "FRANCEBLEU_GASCOGNE",
                    "title": "France Bleu Gascogne",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbgascogne-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=26",
                },
                {
                    "id": "FRANCEBLEU_GIRONDE",
                    "title": "France Bleu Gironde",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbgironde-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=27",
                },
                {
                    "id": "FRANCEBLEU_HERAULT",
                    "title": "France Bleu Hérault",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbherault-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=28",
                },
                {
                    "id": "FRANCEBLEU_ISERE",
                    "title": "France Bleu Isère",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbisere-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=29",
                },
                {
                    "id": "FRANCEBLEU_LA_ROCHELLE",
                    "title": "France Bleu La Rochelle",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fblarochelle-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=30",
                },
                {
                    "id": "FRANCEBLEU_LIMOUSIN",
                    "title": "France Bleu Limousin",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fblimousin-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=31",
                },
                {
                    "id": "FRANCEBLEU_LOIRE_OCEAN",
                    "title": "France Bleu Loire Océan",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbloireocean-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=32",
                },
                {
                    "id": "FRANCEBLEU_SUR_LORRAINE",
                    "title": "France Bleu Sud Lorraine",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbsudlorraine-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=33",
                },
                {
                    "id": "FRANCEBLEU_MAYENNE",
                    "title": "France Bleu Mayenne",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbmayenne-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=34",
                },
                {
                    "id": "FRANCEBLEU_NORD",
                    "title": "France Bleu Nord",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbnord-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=36",
                },
                {
                    "id": "FRANCEBLEU_NORMANDIE_CAEN",
                    "title": "France Bleu Normandie (Calvados - Orne)",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbbassenormandie-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=37",
                },
                {
                    "id": "FRANCEBLEU_NORMANDIE_ROUEN",
                    "title": "France Bleu Normandie (Seine-Maritime - Eure)",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbhautenormandie-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=38",
                },
                {
                    "id": "FRANCEBLEU_ORLEANS",
                    "title": "France Bleu Orléans",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fborleans-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=39",
                },
                {
                    "id": "FRANCEBLEU_PAYS_D_AUVERGNE",
                    "title": "France Bleu Pays d'Auvergne",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbpaysdauvergne-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=40",
                },
                {
                    "id": "FRANCEBLEU_PAYS_BASQUE",
                    "title": "France Bleu Pays Basque",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbpaysbasque-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=41",
                },
                {
                    "id": "FRANCEBLEU_PAYS_DE_SAVOIE",
                    "title": "France Bleu Pays de Savoie",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbpaysdesavoie-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=42",
                },
                {
                    "id": "FRANCEBLEU_PERIGORD",
                    "title": "France Bleu Périgord",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbperigord-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=43",
                },
                {
                    "id": "FRANCEBLEU_PICARDIE",
                    "title": "France Bleu Picardie",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbpicardie-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=44",
                },
                {
                    "id": "FRANCEBLEU_PROVENCE",
                    "title": "France Bleu Provence",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbprovence-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=45",
                },
                {
                    "id": "FRANCEBLEU_ROUSSILLON",
                    "title": "France Bleu Roussillon",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbroussillon-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=46",
                },
                {
                    "id": "FRANCEBLEU_TOURAINE",
                    "title": "France Bleu Touraine",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbtouraine-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=47",
                },
                {
                    "id": "FRANCEBLEU_VAUCLUSE",
                    "title": "France Bleu Vaucluse",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbvaucluse-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=48",
                },
                {
                    "id": "FRANCEBLEU_AZUR",
                    "title": "France Bleu Azur",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbazur-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=49",
                },
                {
                    "id": "FRANCEBLEU_LORRAINE_NORD",
                    "title": "France Bleu Lorraine Nord",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fblorrainenord-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=50",
                },
                {
                    "id": "FRANCEBLEU_POITOU",
                    "title": "France Bleu Poitou",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbpoitou-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=54",
                },
                {
                    "id": "FRANCEBLEU_PARIS",
                    "title": "France Bleu Paris",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fb1071-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=68",
                },
                {
                    "id": "ELSASS",
                    "title": "France Bleu Elsass",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbelsass-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=90",
                },
                {
                    "id": "FRANCEBLEU_MAINE",
                    "title": "France Bleu Maine",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbmaine-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=91",
                },
                {
                    "id": "FRANCEBLEU_TOULOUSE",
                    "title": "France Bleu Occitanie",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbtoulouse-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=92",
                },
                {
                    "id": "FRANCEBLEU_SAINT_ETIENNE_LOIRE",
                    "title": "France Bleu Saint-Étienne Loire",
                    "description": "",
                    "liveStream": "https://icecast.radiofrance.fr/fbstetienne-midfi.mp3?id=openapi",
                    "playerUrl": "https://embed.radiofrance.fr/francebleu/player?id_station=93",
                },
            ],
            "webRadios": None,
        },
    ]
}
